# Generated by Django 3.1.4 on 2021-04-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_owner',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('Username', 'Username')], max_length=255, null=True),
        ),
    ]
