# Generated by Django 3.1.4 on 2021-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('C', 'Cancelled')], default='P', max_length=50, null=True),
        ),
    ]
