# Generated by Django 3.1.4 on 2021-04-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210430_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_comment',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_score',
        ),
    ]
