# Generated by Django 3.0 on 2021-04-30 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_remove_comment_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='newcomments',
            field=models.ManyToManyField(blank=True, related_name='newcomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
