# Generated by Django 3.0 on 2021-04-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210430_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendingcomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Comment')),
            ],
        ),
    ]
