# Generated by Django 3.1.4 on 2021-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210501_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_subject',
            field=models.CharField(choices=[('Biology', ' Biology'), ('Math', 'Math'), ('Chemistry', 'Chemistry'), ('Java', 'Java'), ('Python', 'Python'), ('NLP', 'NLP'), ('Principles Of Programming Language', 'Principles Of Programming Language'), ('Engineering Statistic', 'Engineering Statistic'), ('Internet of Things', 'Internet of Things'), ('Computer Network', 'Computer Network'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
