# Generated by Django 3.0 on 2021-05-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210502_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='registereduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.RegisteredUser'),
        ),
    ]
