# Generated by Django 3.0 on 2021-05-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_comment_registereduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='registereduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.RegisteredUser'),
        ),
    ]
