# Generated by Django 3.0 on 2021-04-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=255, null=True)),
                ('note_subject', models.CharField(choices=[('Biology', ' Biology'), ('Math', 'Math'), ('Chemistry', 'Chemistry'), (' Java', ' Java'), ('Python', 'Python'), ('NLP', 'NLP')], max_length=255, null=True)),
                ('note_description', models.TextField()),
                ('note_status', models.CharField(choices=[('A', 'Approved'), ('C', 'Cancelled')], default='C', max_length=50, null=True)),
                ('note_comment', models.TextField()),
                ('note_score', models.DecimalField(decimal_places=0, max_digits=1, max_length=5, null=True)),
                ('note_pagenumber', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=100, null=True)),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.RegisteredUser')),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
                'ordering': ['user_type'],
            },
        ),
        migrations.CreateModel(
            name='NoteImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='registereduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.RegisteredUser'),
        ),
        migrations.CreateModel(
            name='FavoriteNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_note', to='home.Note')),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.RegisteredUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Note')),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.RegisteredUser')),
            ],
        ),
    ]
