# Generated by Django 3.0 on 2021-05-01 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pendingcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingcomments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pendingcomments',
            name='pendingcomment',
        ),
        migrations.AddField(
            model_name='pendingcomments',
            name='comment_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingcomments',
            name='note_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
