# Generated by Django 3.1.4 on 2021-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210502_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_score',
            field=models.IntegerField(default=0),
        ),
    ]
