# Generated by Django 3.1.4 on 2021-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_note_note_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
