# Generated by Django 3.0 on 2021-05-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210510_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='registereduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.RegisteredUser'),
        ),
    ]
