# Generated by Django 3.0 on 2021-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210514_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritenote',
            name='fav_note',
        ),
        migrations.RemoveField(
            model_name='favoritenote',
            name='registereduser',
        ),
        migrations.DeleteModel(
            name='PendingComments',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_subject',
            field=models.CharField(choices=[('Biology', ' Biology'), ('Math', 'Math'), ('English', 'English'), ('Android Programming', 'Android Programming'), ('History', 'History'), ('Operating Systems', 'Operating Systems'), ('Formations of Modernity', 'Formations of Modernity'), ('Systems Programming', 'Systems Programming'), ('Chemistry', 'Chemistry'), ('Java', 'Java'), ('Database Systems', 'Database Systems'), ('Computer Organization', 'Computer Organization'), ('Python', 'Python'), ('Discrete Mathematics', 'Discrete Mathematics'), ('NLP', 'NLP'), ('Logic Design', 'Logic Design'), ('Linear Algebra', 'Linear Algebra'), ('Principles Of Programming Language', 'Principles Of Programming Language'), ('Engineering Statistic', 'Engineering Statistic'), ('Internet of Things', 'Internet of Things'), ('Computer Network', 'Computer Network'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='FavoriteNote',
        ),
    ]
